
(use-package newsticker
  :custom
  (newsticker-url-list '(
                          ("XKCD" "https://xkcd.com/rss.xml")
                          ("Oatmeal" "https://feeds.feedburner.com/oatmealfeed")
                          ("Julia Evans" "https://jvns.ca/atom.xml")
                          ("Bootlin" "https://bootlin.com/feed/")
                          ("Sacha Chua" "https://sachachua.com/blog/category/emacs/feed/")
                          ("Sean Davis" "https://bluesabre.org/feed/")
                          ("Rebble" "https://rebble.io/feed.xml")
                          ("This Week in Rust" "https://this-week-in-rust.org/rss.xml")
                          ("Purism" "https://puri.sm/feed/")
                          ("Redox OS" "https://www.redox-os.org/news/index.xml")
                          ("Rust Embedded" "https://rust-embedded.github.io/blog/rss.xml")
                          ("Ocaml" "https://ocaml.org/feed.xml" )
                          ("Azeria Labs" "https://azeria-labs.com/feed/")
                          ("seL4 Releases" "https://github.com/seL4/seL4/releases.atom")
                          ("Alan Petitepomme" "https://alan.petitepomme.net/cwn/cwn.rss")
                          ("Evan Sultanik" "https://feeds.feedburner.com/EvanSultanik")
                          ("RISC-V" "https://riscv.org/feed")
                          ("System 76" "https://blog.system76.com/rss")
                          ("It's Foss" "https://feeds.feedburner.com/ItsFoss")
                          ("Improbable Research"
                           "https://feeds.feedburner.com/ImprobableResearch")
                          ("Live Kindly" "https://www.livekindly.com/feed/")
                          ("Vegan News" "https://vegnews.com/news/todays-top-stories/feed.rss")
                          ("Embedded Artistry" "https://embeddedartistry.com/feed/")
                          ("Schneier Security" "https://www.schneier.com/blog/atom.xml")
                          ("EFF" "https://www.eff.org/rss/updates.xml")
                          ("Amos Blog" "https://amos.me/index.xml")
                          ("OS Blog" "https://web.eecs.utk.edu/~smarz1/osblog/feed.rss")
                          ("Japaric's Blog" "https://blog.japaric.io/index.xml")
                          ("Politico" "https://www.politico.com/rss/politicopicks.xml")
                          ("Boing Boing - Cory Doctorow"
                           "https://boingboing.net/author/cory_doctorow_1/feed")
                          ("CNX Software "
                           "https://feeds.feedburner.com/cnx-software/blog?format=xml")
                          ("Linux Gizmos" "https://linuxgizmos.com/feed/")
                          ("Toggl Comics" "https://toggl.com/blog/track/creative/feed")
                          ("Righto Blog" "https://www.righto.com/feeds/posts/default")
                          ("Microkernel Dude" "https://microkerneldude.wordpress.com/feed/")
                          ("Genode Blog" "https://genode.org/news/aggregator/rss")
                          ("Genodians" "https://genodians.org/rss")
                          ("Emacs Redux" "https://emacsredux.com/atom.xml")
                          ("Urban Dictionary"
                           "https://feeds.urbandictionary.com/UrbanWordOfTheDay")
                          ("Restore Privacy" "https://restoreprivacy.com/feed")
                          ("Mega Beets" "https://www.megabeets.net/feed/")
                          ("Rizin" "https://rizin.re/posts/index.xml")
                          ("Dialy Writing Tips" "https://www.dailywritingtips.com/feed/")
                          ("Beningo Blog" "https://www.beningo.com/feed/")
                          ("Bridge MI" "https://www.bridgemi.com/rss.xml")
                          ("Pluralistic" "https://pluralistic.net/feed/")
                          ("Tecosaur" "https://blog.tecosaur.com/tmio/rss.xml")
                          ("Citizen" "https://citizen.org/feed")
                          ("Element Blog" "https://element.io/blog/rss/")
                          ("Matrix Blog" "https://matrix.org/blog/feed")
                          ("Interrupt Memfault Blog" "https://interrupt.memfault.com/feed.xml")
                          ("Athea" "https://blog.althea.net/rss")
                          ("OMG Ubuntu" "https://omgubuntu.co.uk/feed")
                         )
                       )
  )
